### K값의 중요성
- k = 근접 이웃 개수(근접 이웃 몇개를 선택할 것인지)
- k값을 선택하면서 시행착오를 겪어야 함
- k값에 따라서 분류 결과 달라짐
- k값에 따라서 전확도와 신뢰도가 달라짐

### KNN모델
- KNeighborsClassifier() = 분류기로 사용
- Regressor = 연속형 데이터 예측
- KNeighborsRegressor() = 연속형 값 예측

### 호감도 LABEL 예측 모델

In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

### 데이터 읽어오기

In [5]:
like = pd.read_csv(r'C:\Users\User\Desktop\머신러닝 학습\KNN 학습\like.csv')
like.columns = ['talk', 'book', 'travel', 'school', 'tall', 'skin', 'muscle', 'like_level']
like.head()

talk  book  travel  school  tall  skin  muscle like_level
0    30    80      40      40    90    90      50        1타입
1    60    50      70      50    60    60      90        2타입
2    50    40      80      60    50    70      80        2타입
3    90    50      60      30    40    20      30        3타입
4    50    70      30      70    70    80      60        1타입

### 입력과 target데이터를 분리한다

In [9]:
x = np.array(like.drop('like_level', axis=1))
print(x.shape)
y = np.array(like.like_level)
print(y.shape)

(14, 7)
(14,)


In [10]:
y.shape, x.shape

((14,), (14, 7))

In [11]:
x

array([[30, 80, 40, 40, 90, 90, 50],
       [60, 50, 70, 50, 60, 60, 90],
       [50, 40, 80, 60, 50, 70, 80],
       [90, 50, 60, 30, 40, 20, 30],
       [50, 70, 30, 70, 70, 80, 60],
       [70, 30, 60, 40, 40, 40, 30],
       [40, 90, 60, 60, 60, 80, 60],
       [30, 60, 90, 60, 40, 70, 70],
       [80, 40, 20, 80, 60, 40, 50],
       [50, 70, 70, 50, 70, 90, 50],
       [80, 50, 60, 40, 50, 40, 70],
       [30, 70, 30, 90, 70, 80, 60],
       [40, 60, 90, 60, 50, 70, 80],
       [80, 30, 50, 50, 80, 40, 60]], dtype=int64)

In [12]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

### - KNN은 데이터가 많지 않아도 모델을 만들 수 있다는 장점이 있다

### 데이터를 정규화한다

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # 정규화를 시켜준다
scaler.fit(x)

x = scaler.transform(x)

In [14]:
# 데이터의 정기화
# talk,book,travel,school,tall,skin,muscle같이 스케일이 달라도 
# 동등한 입장에서 모델을 만들 수 있다
x

array([[-1.26962211,  1.34164079, -0.8461218 , -0.98782916,  2.06644812,
         1.29927838, -0.59160798],
       [ 0.21160368, -0.36590203,  0.57536283, -0.3592106 ,  0.04805693,
        -0.09994449,  1.77482393],
       [-0.28213825, -0.93508297,  1.04919104,  0.26940795, -0.62474013,
         0.36646313,  1.18321596],
       [ 1.69282948, -0.36590203,  0.10153462, -1.61644772, -1.29753719,
        -1.96557498, -1.77482393],
       [-0.28213825,  0.77245985, -1.31995001,  0.89802651,  0.720854  ,
         0.83287076,  0.        ],
       [ 0.70534562, -1.50426391,  0.10153462, -0.98782916, -1.29753719,
        -1.03275974, -1.77482393],
       [-0.77588018,  1.91082173,  0.10153462,  0.26940795,  0.04805693,
         0.83287076,  0.        ],
       [-1.26962211,  0.20327891,  1.52301925,  0.26940795, -1.29753719,
         0.36646313,  0.59160798],
       [ 1.19908755, -0.93508297, -1.79377823,  1.52664507,  0.04805693,
        -1.03275974, -0.59160798],
       [-0.28213825,  0.7724

### KNN 분류기 모델을 만든다
- 범주형 데이터를 예측하는 모델

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x,y)

KNeighborsClassifier()

In [16]:
y_pred = classifier.predict(x)
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [17]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

### 모델을 평가한다

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y,y_pred)) #평가는 혼돈행령 사용 :
                                  #결과값이 대각선 방향에 숫자가 모여 있어야 한다
print(classification_report(y,y_pred))

[[5 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

         1타입       1.00      1.00      1.00         5
         2타입       1.00      1.00      1.00         4
         3타입       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14

